- 😄 Pronouns: He/Him
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- Exporing Modern Data Stack (BigData, Airflow, Spark,Databricks)
- Azure and GCP Cloud
- 💞️ I’m looking to collaborate on ...
- 📫 Here's how you can reach me: LinkedIn
- ⚡ Fun fact: ...

<!---
Praveen-Halapeti/Praveen-Halapeti is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
